-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 09d1747840bfb1457e9b8876b4c1f577d00a2a37
    hooks:
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --max-line-length=131
        - --ignore=W503
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - --ignore=W503
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: git://github.com/asottile/reorder_python_imports.git
    sha: b022734351abe44d0b05a71a4fa1175287c59b49
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --remove-import
        - from __future__ import with_statement
